# Generated by Django 4.1.7 on 2023-02-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20, unique=True)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.menu')),
            ],
        ),
    ]
